[package]
name = "gnome-randr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.5"
bitflags = "1.3.2"
structopt = "0.3.23"
